apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ctarvzwi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ctarvzwi:16d02bc55df29605a462f229772e1adc8409d932@sha256:7e5d6680c05f22969b23d645f611ce4e2358a2495210acea233c81a2113178e5
          name: container-image
